version: "3.9"

services:
  client:
    container_name: "chat_client"
    build:
      context: "./client"
    ports:
      - "3000:3000"

  server:
    container_name: "chat_server"
    build:
      context: "./server"
    ports:
      - "3003:3003"